name: Unity Actions
on:
    push:
        branches: [releases]
jobs:
test:
    runs-on: ubuntu-latest
    strategy:
    fail-fast: false
    steps:
    - name: test
    - uses: game-ci/unity-test-runner@v2
env:
    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
    with:
    projectPath: GAMEPROJ2
    githubToken: ${{ secrets.GITHUB_TOKEN }}
