name: Unity Actions
on:
    push:
        branches: [releases]
jobs:
test:
    runs-on: ubuntu-latest
    strategy:
    fail-fast: false
    steps:
    -name: test
    - uses: game-ci/unity-test-runner@v2
  env:
    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  with:
    projectPath: GAMEPROJ2
    githubToken: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v2
  if: always()
  with:
    name: Test results
    path: artifacts
    - uses: actions/cache@v2
  with:
    path: GAMEPROJ2/Library
    key: Library-MyProjectName-TargetPlatform
    restore-keys: |
      Library-MyProjectName-
      Library-
